version: '3'
name: gazer

services:
  site:
    build:
      dockerfile: apps/ui/Dockerfile
      context: .
    ports:
      - '8080:80'
    volumes:
      - './images:/src/public'
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
  server:
    build:
      dockerfile: apps/server/Dockerfile
      context: .
    logging:
      driver: local
    env_file: .env
    environment:
      DATABASE_HOST: postgres
    volumes:
      - './images:/src/images'
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
  migrations:
    build:
      dockerfile: apps/cli/Dockerfile
      context: .
    env_file: .env
    environment:
      DATABASE_HOST: postgres
    logging:
      driver: local
    depends_on:
      - postgres
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
  postgres:
    build:
      dockerfile: apps/postgres/Dockerfile
      context: .
    env_file: .env
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
